SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM (SELECT * FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE '%Intact%') A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID AND B.SEX_UPON_OUTCOME NOT LIKE '%Intact%'