-- [1] LEFT JOIN 사용
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.ANIMAL_ID

-- [2] NOT EXISTS 사용
-- SELECT ANIMAL_ID, A.NAME
-- FROM ANIMAL_OUTS A
-- WHERE NOT EXISTS(SELECT * FROM ANIMAL_INS B WHERE A.ANIMAL_ID = B.ANIMAL_ID)