-- [1]LEFT JOIN 사용
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME
LIMIT 3

-- [2]NOT IN 사용
-- SELECT NAME, DATETIME
-- FROM ANIMAL_INS A
-- WHERE A.ANIMAL_ID NOT IN ( SELECT B.ANIMAL_ID FROM ANIMAL_OUTS B )
-- ORDER BY A.DATETIME
-- LIMIT 3