-- [1] CASE, WHEN 사용
SELECT ANIMAL_ID, NAME
    , CASE
        WHEN SEX_UPON_INTAKE LIKE 'Neutered%' OR SEX_UPON_INTAKE LIKE 'Spayed%' THEN 'O'
        ELSE 'X'
    END AS '중성화'
FROM ANIMAL_INS

-- [2] IF, SUBSTRING 사용
SELECT ANIMAL_ID, NAME,
    IF(SUBSTRING(SEX_UPON_INTAKE,1,8) = 'Neutered' 
    OR SUBSTRING(SEX_UPON_INTAKE,1,6) = 'Spayed', 'O', 'X') AS 중성화
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID