# Generated by Django 2.2.6 on 2019-11-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follwers',
            new_name='followers',
        ),
    ]
